export const MIXTURES = [
	'Adjika',
	'Advieh',
	'Baharat',
	'Beau Monde seasoning',
	'Berbere',
	'Bouquet garni',
	'Buknu',
	'Chaat masala',
	'Chaunk',
	'Chili powder',
	'Crab boil',
	'Curry powder',
	'Doubanjiang',
	'Douchi',
	'Duqqa',
	'Fines herbes',
	'Five-spice powder',
	'Garam masala',
	'Garlic powder',
	'Garlic salt',
	'Gochujang',
	'Harissa',
	'Hawaij',
	'Herbes de Provence',
	'Idli podi',
	'Jamaican jerk spice',
	'Khmeli suneli',
	'Lemon pepper',
	'Mitmita',
	'Mixed spice',
	'Montreal steak seasoning',
	'Mulling spices',
	'Old Bay Seasoning',
	'Onion powder',
	'Panch phoron',
	'Persillade',
	'Powder-douce',
	'Pumpkin pie spice',
	'Qâlat daqqa',
	'Quatre épices',
	'Ras el hanout',
	'Recado rojo',
	'Sharena sol',
	'Shichimi',
	'Tabil',
	'Tandoori masala',
	'Vadouvan',
	'Yuzukosho',
	"Za'atar",
];
